import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineMapPin,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiSalesforce,
  SiPython,
  SiPolars,
  SiApachespark,
  SiApachekafka,
  SiApacheairflow,
  SiPostgresql,
  SiMongodb,
  SiDocker,
  SiAmazonwebservices,
  SiTerraform,
  SiScikitlearn,
  SiPandas,
  SiDelta,
  SiDuckdb,
  SiAirbyte,
  SiTalend,
  SiLangchain,
  SiBentoml,
} from "react-icons/si";

import { DiMsqlServer } from "react-icons/di";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineMapPin,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  salesforce: SiSalesforce,
  python: SiPython,
  spark: SiApachespark,
  kafka: SiApachekafka,
  airflow: SiApacheairflow,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  docker: SiDocker,
  aws: SiAmazonwebservices,
  terraform: SiTerraform,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  polars: SiPolars,
  delta: SiDelta,
  duckdb: SiDuckdb,
  airbyte: SiAirbyte,
  talend: SiTalend,
  langchain: SiLangchain,
  bentoml: SiBentoml,
  mssql: DiMsqlServer,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
